name: ci

on:
  push:
    branches: master

jobs:
  multi:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup script
        uses: docker/build-push-action@v2
        with:
          context: '1'
          file: ./Dockerfile
          push: true
          tags: |
            yogen48/simple-flask-app:latest
